(in-package :cl-user)

(defpackage :sigma
  (:use :cl :cl-user)
  (:export #:filter-symbol ;;START MAIN
	   #:not-equal-symbol
	   #:infinity
	   #:max-time
	   #:max-state
	   #:continuous-max
	   #:boolean-true 
	   #:boolean-false
	   #:sense-positive
	   #:sense-negative
	   #:negation-symbol
	   #:best-symbol
	   #:distribution-symbol
	   #:expected-symbol
	   #:prob-match-symbol 
	   #:exponential-symbol
	   #:interrupt-symbol 
	   #:halt-symbol 
	   #:prediction-suffix 
	   #:episodic-suffix 
	   #:temporal-predicate-name 
	   #:concat-symbols
	   #:temporal-predicate-name-episodic
	   #:halt-predicate-name 
	   #:var-index
	   #:fact-index
	   #:depth-queues-index
	   #:other-queue-index
	   #:category-symbol 
	   #:system-predicates
	   #:bp-nodes
	   #:bp-graph
	   #:*bp-node-stream*
	   #:*nodes-depth* 
	   #:*main-pinboard*
	   #:*selected-node* 
	   #:display-subgraph 
	   #:*node-stream*
	   #:graph-alpha 
	   #:parameter-name
	   #:global-parameters
	   #:parameter-override-reset
	   #:parameter
	   #:default-temperature
	   #:trial-count
	   #:log-trials 
	   #:trace-stream
	   #:from-regression
	   #:regression-interface
	   #:from-parallel
	   #:*parallel-interface*
	   #:*info-stream* 
	   #:info-stream 
	   #:reset-parameters-in-init 
	   #:track-time 
	   #:reset-parameters 
	   #:cg
	   #:bottom-state
	   #:message-count
	   #:decision-count
	   #:temperature 
	   #:one-over-temperature
	   #:epsilon21
	   #:relative-epsilon
	   #:smooth-plm-subthreshold-regions
	   #:global-graph-messages
	   #:have-run
	   #:perceive-list
	   #:perceive-list
	   #:action-list
	   #:action-list
	   #:pre-run
	   #:pre-run 
	   #:post-run
	   #:post-run
	   #:pre-d
	   #:pre-d
	   #:post-d
	   #:post-d
	   #:pre-t 
	   #:pre-t 
	   #:post-t
	   #:post-t
	   #:post-automatic
	   #:post-automatic 
	   #:pre-ts 
	   #:pre-ts 
	   #:global-decision-statistics 
	   #:selected-operator-wipe
	   #:number-of-messages 
	   #:sum-of-message-times
	   #:maximum-message-time
	   #:add-new-state
	   #:delete-lower-states
	   #:impasse-regions
	   #:data-set-attributes
	   #:data-set-category 
	   #:do-not-learn 
	   #:define-system-predicate 
	   #:graph 
	   #:queue 
	   #:node 
	   #:factor-step
	   #:beta-memories 
	   #:descendant 
	   #:descendant-link
	   #:link 
	   #:message 
	   #:smap 
	   #:conditional
	   #:predicate 
	   #:vector-symbol
	   #:vector-argument 
	   #:argument-vector 
	   #:sqrt-function 
	   #:plm 
	   #:region 
	   #:dimension
	   #:slice 
	   #:stype 
	   #:svariable 
	   #:affine 
	   #:decision-statistics
	   #:pattern-variable 
	   #:conditional 
	   #:conditional-from-name 
	   #:new-type
	   #:type-from-name
	   #:type-from-predicate-argument
	   #:best-variable
	   #:expected-variable
	   #:distribution-variable
	   #:selection-variable 
	   #:multiple-variable 
	   #:non-multiple-variable 
	   #:variable-from-name 
	   #:union-two-variables
	   #:union-variables 
	   #:multiple-from-predicate-argument
	   #:position-of-predicate-argument 
	   #:has-operator-argument 
	   #:argument-name 
	   #:argument-type-name
	   #:argument-tail 
	   #:argument-symbol
	   #:best-argument 
	   #:distribution-argument
	   #:prob-match-argument 
	   #:exponential-argument
	   #:expected-argument 
	   #:selection-argument 
	   #:multiple-argument
	   #:unique-argument
	   #:argument-select
	   #:state-argument 
	   #:check-predicate-arguments
	   #:predicate-universal
	   #:predicate-cumulative
	   #:argument-to-element 
	   #:open-world
	   #:closed-world 
	   #:predicate-from-name
	   #:perception-node-from-name
	   #:prediction-argument
	   #:convert-to-wm-variable-name
	   #:goal
	   #:predicate
	   #:system-predicate
	   #:state-predicate 
	   #:operator-selection
	   #:nstars
	   #:stars
	   #:regions-in-plm 
	   #:init-vpoint-map
	   #:empty-node-function
	   #:var-type-index
	   #:chunk-pattern
	   #:create-chunk 
	   #:create-chunks
	   #:count-operators-predicate
	   #:count-operators 
	   #:make-predicate-operator 
	   #:init-operators
	   #:init-checks 
	   #:init 
	   #:halt
	   #:haltp
	   #:inactive-link
	   #:excise-inactive-links
	   #:excise-unneeded-factor-steps-node
	   #:excise-unneeded-factor-steps 
	   #:include-prediction-links 
	   #:init-descendants 
	   #:predicate-function-unique-arguments 
	   #:assign-variables-same 
	   #:post-process-conditionals
	   #:init-node-vector 
	   #:init-graph
	   #:ig
	   #:unique-model-arguments
	   #:universal-arguments
	   #:create-action-models
	   #:create-perception-models
	   #:create-models 
	   #:best-in-plm 
	   #:nonstate-value 
	   #:value-in-function-state 
	   #:value-in-state
	   #:operator-in-state
	   #:get-symbol-name 
	   #:dimension-full-scope
	   #:variable-types
	   #:region-within-limits
	   #:compute-limits 
	   #:validate-summarize-list
	   #:apply-summarization-arguments
	   #:apply-summarization
	   #:apply-summarizations
	   #:find-plm
	   #:function-region
	   #:plm-cpt
	   #:reusable-conditional-function-c
	   #:reusable-conditional-function
	   #:operator-predicate
	   #:pid
	   #:pids
	   #:active-variables
	   #:count-active-link-directions
	   #:max-node-variables
	   #:count-node-variables
	   #:count-node-links
	   #:count-plm-regions
	   #:cplmr
	   #:vn-posterior
	   #:vnp 
	   #:factor-outgoing-link
	   #:predicate-wm-vns 
	   #:exp-weights
	   #:q
	   #:average-run
	   #:*global-variables* 
	   #:mm ;; END MAIN
           #:add-node
           #:leaf-node
           #:add-link
           #:init-variable-node
           #:var-in-lov
           #:vars-in-lov
           #:build-smap-vfactor
           #:build-smap-fvar
           #:build-smap-omitted
           #:build-smap
           #:variable-subset-order-compatible
           #:init-factor-node
           #:create-graph
           #:node-from-name
           #:node-from-number
           #:nfn
           #:node-function-from-number
           #:nffn
           #:link-from-nodes
           #:dimension-min
           #:dimension-max
           #:dimension
           #:dimension-span
           #:link-from-numbers
           #:node-neighbors
           #:link-node
           #:link-var-node
           #:link-fact-node
           #:link-content
           #:link-var-content
           #:link-fact-content
           #:wm-nodep
           #:wm-fnp
           #:ess-wm-fnp
           #:function-nodep
           #:perception-functionp
           #:node-dependencies-recur
           #:node-dependencies
           #:function-dependencies
           #:wm-dependencies
           #:ess-wm-dependencies
           #:add-node-descendant
           #:copy-descendants
           #:union-descendants
           #:descendants-recur
           #:descendants-recur-no-parents
           #:descendants
           #:init-node-descendants
           #:common-descendants-recur
           #:init-node-descendants-no-parents
           #:node-name-list
           #:link-recur
           #:init-link-descendants
           #:create-subgraph-for-densely-connected-variable-nodes
           #:compile-predicate-function
           #:make-name-string
           #:make-name-symbol
           #:make-name-number-symbol
           #:element-argument-name
           #:element-content
           #:element-rest
           #:element-value
           #:constant-element-regionp
           #:constant-element
           #:variable-element
           #:star-element
           #:element-wm-index
           #:constant-index
           #:compute-span
           #:cpt-region
           #:cpt-plm
           #:random-cpt
           #:cpt-constantp
           #:variables-discretep
           #:variable-dimensions
           #:init-farray
           #:inc-index
           #:region-mins-l
           #:region-maxs-l
           #:delete-duplicates-slice-list
           #:delete-duplicates-slice-list-array
           #:sort-slice-list
           #:sort-slice-list-array
           #:index-slice-list
           #:index-slice-list-array
           #:region-min-slice-indexes-l
           #:region-max-slice-indexes-l
           #:update-function-array-region
           #:cpt-function-array
           #:cpt-function-array-plm
           #:rml-plm
           #:find-region
           #:create-assign-id-function-recur
           #:create-assign-id-function
           #:assign-ids-to-predicate
           #:eliminate-vars-if-not-named
           #:insert-symbol-list
           #:variable-list-name
           #:variable-names
           #:not-empty-vector
           #:merge-variable-vectors-recur
           #:merge-variable-vectors
           #:delta-variables
           #:number-list
           #:create-delta-factor
           #:transform-variables
           #:transform-factor-variables
           #:create-transform-factor
           #:weight-list
           #:span-e=
           #:compatible-constants
           #:create-wm-variable-node
           #:elements-constants
           #:condition-variable-node
           #:add-action
           #:excise-link
           #:add-condition
           #:compute-vector-gradient
           #:selection-variables
           #:negated-constant
           #:create-element-plm
           #:extend-vector
           #:filter-listp
           #:filter-span
           #:filter-constant
           #:filter-coef
           #:create-filter-function
           #:affine-listp
           #:not-equal-listp
           #:pattern-type
           #:variable-unique-in-pattern
           #:variable-unique-in-patterns
           #:variable-unique-in-conditional
           #:variables-equal
           #:shared-filter-wmvn
           #:shared-negation-wmvn
           #:delta-variables-equal
           #:delta-variable-vectors-equal
           #:shared-delta-wmvn
           #:argument-from-variable
           #:create-alpha-network
           #:beta-not-equal-vars-nums
           #:create-beta-not-equal-function
           #:create-beta-network
           #:beta-factor
           #:pattern-variable-data
           #:get-pattern-variable-wm-memory
           #:find-link
           #:create-message
           #:remove-links
           #:get-pattern-variable-name
           #:argument-missing
           #:compile-predicate-pattern
           #:compile-patterns
           #:verify-predicate-pattern
           #:verify-patterns
           #:pp-variable-names
           #:all-variable-names
           #:later-variable-names
           #:function-variable-names
           #:max-discrete-volume
           #:conditional-function-node-name-from-conditional-name
           #:cfn
           #:find-action-variable-type
           #:copy-conditional-function
           #:union-lists
           #:compile-conditional-function
           #:v-type
           #:vs-volume
           #:reorder-conditions
           #:compile-conditional
           #:vector-sum
           #:vector-difference
           #:vector-divide
           #:vector-divide-0
           #:vector-e=
           #:vector-or
           #:vector-not
           #:vector-all-t
           #:init-vector
           #:make-spanning-dimension
           #:make-spanning-dimensions
           #:make-spanning-region
           #:make-discrete-region
           #:make-dps-list
           #:initial-slice-vector
           #:make-region-array
           #:list-of-constant
           #:make-constant-discrete-plm
           #:region-array-origin
           #:plm-origin
           #:init-plm
           #:plm-size
           #:vector-1
           #:init-plm-with-slices
           #:init-plm-from-plm
           #:region-min-slice
           #:region-min
           #:region-max-slice
           #:region-max
           #:region-span
           #:region-volume
           #:region-weight
           #:region-discrete
           #:region-rank
           #:node-rank
           #:beforep
           #:overlapp
           #:within-dimension
           #:within-region
           #:regions-overlap
           #:dimension-extent
           #:equal-extentp
           #:start-beforep
           #:end-afterp
           #:max-region-mins
           #:min-region-maxs
           #:constant-equal
           #:weight-equal
           #:function-equal
           #:copy-function
           #:region-function-constantp
           #:function-constantp
           #:copy-region-full
           #:slice=
           #:slice-member
           #:slice-remove
           #:e=
           #:ae=
           #:e>=
           #:e<=
           #:e>
           #:e<
           #:region-is-variable
           #:region-is-constant
           #:plm-is-constant
           #:region-e-empty
           #:empty-region
           #:region-e-full
           #:region-e-uniform
           #:dimension-active
           #:dimension-inactive
           #:function-constant
           #:region-exhaustive
           #:plm-empty
           #:plm-full
           #:plm-uniform
           #:slices-e=
           #:slice-lists-e=
           #:slice-vectors-equal-length
           #:slice-vectors-e=
           #:region-e=
           #:plm-e=
           #:region-weights
           #:assign-function
           #:extract-function
           #:region-sliced
           #:slice-at-region-min
           #:slice-at-region-max
           #:slice-borders-region
           #:sets-equal
           #:regions-equal
           #:average-function
           #:xor
           #:average-region-functions
           #:slice-is-extreme
           #:extreme-slice
           #:remove-unneeded-slices-from-list
           #:original-from-new-index
           #:copy-dimensions
           #:copy-a-region
           #:rmi-before-ri
           #:rmi-after-ri
           #:region-after-index-vector
           #:region-after-index-list
           #:region-before-index-list-x
           #:region-after-index-list-x
           #:next-index-list
           #:next-index-list-no-d
           #:next-index-vector
           #:region-index-mins
           #:region-after-old
           #:init-needed-vector
           #:slice-needed
           #:slices-needed-by-slice
           #:slices-needed
           #:all-needed
           #:remove-unneeded-slices
           #:eintegerp
           #:discretize-dimension
           #:factor-plm-by-dimensions
           #:element-from-index-vector
           #:update-regions-in-span-recur
           #:update-regions-in-span
           #:find-slice-at-location-v
           #:find-slice-index-v
           #:find-slice-at-location
           #:find-slice-index
           #:find-region-index
           #:find-region-slice-at-location
           #:find-region-slice-index
           #:check-universal-dimension-weights
           #:update-region
           #:merge-slice-lists
           #:merge-slice-vectors
           #:cross-index-slice-lists
           #:cross-index-slice-vector
           #:index-list-from-cross-index
           #:index-list-from-cross-index-list
           #:no-corresponding-region
           #:apply-slices
           #:factor-plm
           #:linear-value
           #:exponential-value
           #:outer-product
           #:quadratic-value
           #:linear-slope
           #:mean
           #:region-mins-0
           #:region-mins
           #:region-maxs
           #:region-mids
           #:slope-approximation-points
           #:approximation-error
           #:constant-approximation-points
           #:first-max-region-functions
           #:first-max-functions
           #:product-functions
           #:max-functions
           #:por-functions
           #:divide-functions
           #:divide-0-functions
           #:gdl-scale
           #:within-bounds
           #:point-in-plm
           #:region-point-index
           #:region-point
           #:plm-type-check
           #:plm-volume
           #:plm-non-empty
           #:sparse-merge-slices
           #:count-up-vector
           #:find-sparse-slices
           #:find-sparse-slices-reverse
           #:sparse-region-index
           #:sparse-product-plms
           #:sparse-product-plms-reverse
           #:tsp
           #:combine-regions
           #:combine-plms
           #:product-plms
           #:variable-posterior
           #:maximum-in-region
           #:maximum-in-plm
           #:scale-to-one-plm
           #:init-outer-plm
           #:outer-region-weights
           #:outer-combine-regions
           #:outer-plms
           #:product-outer-plms
           #:init-summarize-plm
           #:region-volume-function
           #:summarize-region
           #:summarize-plm
           #:integral-point-linear
           #:integral-point-exponential
           #:integral-region
           #:integral-plm
           #:arg-true
           #:maximize-region
           #:maximal-elements-region
           #:average
           #:vector-average
           #:dominates-region
           #:maximum-region
           #:maximize-plm
           #:extract-value-region
           #:extract-value-combine
           #:extract-value-plm
           #:unique-dimensions
           #:normalize-plm
           #:minimum-point
           #:maximum-point
           #:region-extreme
           #:region-above-threshold-p
           #:region-volume-ds
           #:span-above-threshold-region
           #:span-above-threshold-plm
           #:threshold-plm-destructive
           #:compute-subtractor
           #:subtractive-normalize-plm
           #:continuous-point
           #:expected-element-region
           #:expected-value-region
           #:expected-value-plm
           #:explicit-cpt-entry
           #:explicit-plm
           #:smooth-plm
           #:plm-extreme
           #:average-plm
           #:average-plm-ds
           #:invert-value
           #:invert-function
           #:invert-function-variant
           #:scale-function
           #:negate-function
           #:add-to-function
           #:exponentiate-function
           #:exponentiate-constant-function
           #:exponentiate-constant-times10-function
           #:function-zero
           #:boolean-threshold-function
           #:actually-exponentiate-function
           #:boltzmann-function
           #:boolean-function
           #:transform-region
           #:transform-plm
           #:copy-slice-list
           #:copy-slice-vector
           #:slice-vector-vector
           #:dimension-sizes-from-slices
           #:array-dimensions-v
           #:dimension-sizes-v
           #:dimension-sizes
           #:dimension-multipliers
           #:row-major-index
           #:index-from-row-major
           #:row-major-vector
           #:copy-region-contents
           #:copy-a-plm
           #:reverse-region
           #:reverse-plm
           #:strip-and-reorder-vector
           #:strip-and-reorder-region
           #:srr-original-index
           #:strip-and-reorder-regions
           #:strip-and-reorder-plm
           #:factor-combined-dimensions
           #:diagonal-region
           #:diagonal-slices
           #:diagonalize-region
           #:diag-original-index
           #:diagonalize-plm
           #:next-diagonal-index
           #:zero-diagonal
           #:inverse-diagonalize-plm
           #:init-queue
           #:queue-empty
           #:queue-not-empty
           #:queue-length
           #:depth-queues-length
           #:length-queues
           #:pop-queue
           #:add-to-queue
           #:message-from-numbers
           #:message-function-from-numbers
           #:mffn
           #:message-empty
           #:message-full
           #:message-uniform
           #:combine-messages
           #:transform-message
           #:remove-out-of-bound-slices
           #:affine-dimensions
           #:smallest-maximal-point
           #:translate-plm
           #:offset-print-string
           #:affine-print-string
           #:map-dns
           #:affine-plm
           #:affine-delta-plm
           #:in-order
           #:affine-message
           #:init-var-fact-link-content
           #:init-fact-var-link-content
           #:prequeue
           #:init-outgoing-messages-links
           #:update-outgoing-messages-links
           #:init-link-counts
           #:total-link-counts
           #:init-messages-fresh-stale
           #:initialize-graph-changes
           #:init-graph-messages
           #:update-graph-messages
           #:node-outgoing-messages
           #:reorder-factor-variables
           #:full-depth-message-queues
           #:init-message-queues
           #:wm-change-message
           #:init-messages
           #:im
           #:break-on-positive-messages
           #:message
           #:mp
           #:message-statistics
           #:ms
           #:compute-link-depth
           #:compute-node-link-depths
           #:incoming-links
           #:compute-link-depths
           #:compute-link-loop-depth
           #:compute-node-link-loop-depths
           #:link-loop-edge
           #:node-loop-edge
           #:compute-link-loop-depths
           #:clear-link-depths
           #:compute-all-depths
           #:same-arc
           #:arc-in-queue
           #:arc-in-depth-queues
           #:arc-in-queues
           #:remove-arc-in-queue
           #:depth-message-queues-not-empty
           #:message-queues-not-empty
           #:add-to-message-queue
           #:variable-exists
           #:variable-number
           #:variables-members
           #:other-link
           #:other-incoming-link
           #:outgoing-fact-var-message
           #:use-link-in-var-product
           #:strip-front-useless-links
           #:reorder-variable-product
           #:outgoing-var-fact-message
           #:variable-nodep
           #:factor-nodep
           #:average-message-time
           #:init-message-times
           #:pmt
           #:outgoing-message
           #:next-message-index
           #:incoming-message
           #:pop-depth-message-queues
           #:pop-message-queues
           #:mark-incoming-message
           #:process-one-message
           #:process-message-queue
           #:set-all-but-i
           #:generate-output-vector
           #:generate-node-messages
           #:generate-outgoing-messages
           #:initialize-incoming-marks
           #:elaboration-cycles
           #:interrupt-run
           #:load-queues
           #:run
           #:r
           #:decide
           #:d
           #:rewipe-operators-after-selection
           #:copy-diachronic-perception
           #:compute-goal-progress
           #:trials
           #:ts
           #:get-state-predicate
           #:init-wm
           #:update-wm
           #:empty-wm
           #:empty-wms
           #:wme-region
           #:inverse-args
           #:inverse-region
           #:add-wme
           #:evidence
           #:perceive
           #:update-perception-memories
           #:empty-per
           #:empty-pers
           #:maximize-selection-dimension
           #:constant-weight-vector
           #:set-constant-region
           #:max-min
           #:sum-differences
           #:point-in-maximal-region
           #:multiple-maximals
           #:generate-impasse
           #:maximal-contained
           #:selection-still-maximal
           #:impasse-none
           #:impasse-matches-region
           #:new-impasse-none
           #:selection-variable-list
           #:detect-impasses-state
           #:maximal-subregion
           #:change-wm-selection
           #:selected-region-from-unique-change
           #:change-predicate-wm
           #:change-wm
           #:discrete-point
           #:prob-match-plm
           #:region-changes-plm
           #:regions-change-plm
           #:overlay-region
           #:update-function
           #:shatter-plm
           #:share-slices
           #:empty-plm
           #:full-plm
           #:stype-index
           #:highest-slice
           #:lowest-slice
           #:second-highest-slice
           #:fill-open-world-state
           #:clone-state
           #:agent-name
           #:agent-number
           #:delete-lower-states-function
           #:delete-lower-states-node
           #:delete-lower-states
           #:adjust-states
           #:learn
           #:init-temporal-conditional
           #:convert-argument-open-world
           #:init-predicate-em
           #:no-prediction-predicates
           #:variablize-predicate
           #:convert-argument-predicate-name
           #:convert-arguments-predicate-name
           #:create-reinforcement-learning
           #:trace-gdl
           #:initialize-weighted-gradient
           #:integral-over-all-dimensions-plm
           #:integrate-out-all-but-state-dimension-plm
           #:average-over-all-dimensions-plm
           #:integral-function-message-product
           #:normalize-over-all-dimensions-plm
           #:parent-span
           #:function-span
           #:compute-weighted-gradient
           #:stype-spans
           #:update-via-gradient
           #:update-functions-via-gradient
           #:define-attribute
           #:category-prior
           #:random-vector
           #:normalize-vector
           #:random-distribution
           #:rd
           #:likelihood
           #:define-data-set
           #:init-gd-test-results
           #:total-gd-test-results
           #:find-gd-test-results
           #:update-gd-test-results
           #:setup-gd
           #:instance
           #:check-for-new-constants
           #:find-functions-using-type
           #:update-function-factors
           #:update-max-slice
           #:update-beta-factors
           #:update-wm-factors
           #:cat-init
           #:cat-conds
           #:color-silver
           #:test-color-silver
           #:color-white
           #:alive-true-legs-4
           #:concept-human
           #:weight-200
           #:cat-all
           #:no-legs
           #:no-concept-legs
           #:no-weight
           #:no-concept-weight
           #:cat1
           #:color-silver1
           #:cat1n
           #:legs-2
           #:cat2
           #:color-silver2
           #:ssm
           #:ssm-color-silver
           #:episodic
           #:test-episodic
           #:episodic-replay
           #:test-episodic-replay
           #:random-element
           #:random-episode
           #:random-cwdss-arguments
           #:random-cwdss-predicate
           #:vector-of-types
           #:random-episodic-predicates
           #:random-episodes
           #:episodic-random
           #:init-rule
           #:rule-one
           #:test-rule-one
           #:rule-two
           #:init-rule2
           #:rule-one2
           #:rule-two2
           #:constraint
           #:ct
           #:ce
           #:cl
           #:pepb
           #:ep7i
           #:ep7e
           #:ep7e2
           #:ep7e3
           #:ep7
           #:ep72
           #:ep73
           #:ep8i
           #:ep8
           #:ep82
           #:ep82e
           #:test-eight-puzzle
           #:test-print-eight-puzzle
           #:ep83
           #:ep9i
           #:ep9
           #:ep92
           #:ep93
           #:ep10i
           #:ep102
           #:sa
           #:o1i
           #:o1e
           #:o1e2
           #:o1
           #:o12
           #:test-affine
           #:xta
           #:test-rotate-cond
           #:xtrc
           #:test-rotate-variant
           #:xtrv
           #:mt
           #:mt2
           #:ab
           #:line-detector
           #:line-detector-noise
           #:xldn
           #:smooth
           #:xs
           #:smooth2
           #:xs2
           #:smooth3
           #:xs3
           #:tetris
           #:xt
           #:filter
           #:3dmt
           #:setup-dataset
           #:gdl
           #:simple-gdl
           #:br4
           #:sgdl
           #:ma-grid2
           #:vr
           #:vr2
           #:vr3
           #:vr4
           #:oc
           #:ev
           #:vo
           #:nd
           #:current-location
           #:assign-reward
           #:init-rl-grid7
           #:brief-init-rl-grid7
           #:rl-grid7
           #:test-rl-mb-7
           #:test-rl-dp-7
           #:test-rl-mf-7
           #:rle7
           #:rlr7
           #:test-rl-print
           #:init-rl-grid8
           #:rl-grid8
           #:test-rl-mb
           #:test-rl-dp
           #:test-rl-am
           #:test-rl-mf
           #:rle8
           #:rlr8
           #:assign-reward9
           #:init-rl-grid9
           #:brief-init-rl-grid9
           #:rle9
           #:rlr9
           #:rl-grid9
           #:test-rl-rl
           #:execute-pomdp-operator
           #:init-pomdp
           #:perceive-pomdp1-location
           #:execute-pomdp1-operator
           #:random-transition-fn
           #:init-pomdp1
           #:rd1
           #:init-rw
           #:rrw
           #:test-rw-al
           #:ti
           #:tmi
           #:tma
           #:tf
           #:perceive-diachronic-object
           #:execute-diachronic-operator
           #:diachronic-slam
           #:dsl
           #:test-slam
           #:test-extend-type
           #:test-extend-type1
           #:test-extend-type2
           #:test-extend-type3
           #:define-attribute-pos
           #:pos-tagger-model
           #:train-pos-model
           #:test-pos-model
           #:train-pos-model3
           #:test-pos-model3
           #:pos-tagger-model1
           #:train-pos-model1
           #:test-pos-model1
           #:pos-tagger-model2
           #:tg
           #:tec
           #:tpm
           #:tca
           #:chunk
           #:ado
           #:ado2
           #:ado3
           #:pec
           #:tper
           #:tco
           #:tcs
           #:tmud
           #:tmud2
           #:nav
           #:tna
           #:integer-list
           #:trmi
           #:twve
           #:twvne
           #:tamuv
           #:tcoff
           #:tcwp
           #:tiuwu
           #:run-distributed-negate-single-sentence
           #:run-distributed-negate-two-sentences
           #:run-distributed-negate
           #:distributed-negate
           #:print-node-progenitors
           #:print-link-depths
           #:plds
           #:print-message-times
           #:print-incoming-marks
           #:sum-decision-statistics
           #:rri
           #:print-global-decision-statistics
           #:pgds
           #:print-link-counts
           #:plc
           #:print-link-message-sizes
           #:plms
           #:print-gma
           #:print-gd-test-results
           #:print-svariable
           #:print-function-value
           #:print-dimension
           #:print-maximals
           #:print-region
           #:print-plm-slices
           #:ps
           #:print-one-plm
           #:print-plm
           #:pplm
           #:pplm
           #:space-string
           #:print-centered
           #:print-right-justified
           #:longest-label
           #:compute-label
           #:compute-label-string
           #:print-label
           #:range-label
           #:print-x-headers
           #:parray-print-0d
           #:parray-print-1d
           #:parray-1d
           #:parray-print-2d
           #:parray-2d
           #:parray-print-3d-1
           #:parray-3d
           #:parray-all
           #:parray-print-all
           #:parray-one
           #:parray
           #:pa
           #:print-svariables
           #:print-factor-step
           #:print-factor-steps
           #:print-neighbors
           #:print-node-type
           #:pnt
           #:save-node-functions
           #:print-node
           #:pn
           #:print-message
           #:print-in-messages
           #:pim
           #:print-out-messages
           #:pom
           #:print-link
           #:print-preferences
           #:pprefs
           #:pm
           #:print-factor-function
           #:print-queue-contents
           #:print-queue
           #:pq
           #:print-queues
           #:pqs
           #:print-variable-nodes
           #:pvns
           #:print-factor-nodes
           #:pfns
           #:print-nodes
           #:pns
           #:print-alpha-memories
           #:pam
           #:print-type
           #:pt
           #:print-type-from-name
           #:ptn
           #:print-types
           #:pts
           #:print-predicate
           #:print-predicates
           #:pps
           #:print-predicate-from-name
           #:pp
           #:print-patterns
           #:print-conditional
           #:pc
           #:pcs
           #:pcf
           #:pcfs
           #:ppf
           #:ppfs
           #:pafs
           #:pem
           #:print-episodic-memory
           #:pep
           #:graph-statistics
           #:gs
           #:print-node-names
           #:pnn
           #:print-graph
           #:pg
           #:print-wm-vn
           #:ppvn
           #:print-pred-wm-function
           #:ppwmfn
           #:print-pred-function
           #:ppfn
           #:print-predicate-perception-function
           #:pppfn
           #:pppfns
           #:parrayp
           #:print-pred-wm
           #:ppwm
           #:print-wm
           #:pwm
           #:print-functions
           #:pfs
           #:print-expected-value-cond-function
           #:pevcf
           #:print-expected-value-pred-function
           #:pevpf
           #:graph-message-array
           #:compare-gmas
           #:compare-gma-lists
           #:debug-message
           #:undo-debug-traces
	   #:*example-list*
           #:*font-colors*
           #:color-examples
           #:current-color
           #:*exception*
           #:exception
           #:list-ex
           #:example-directory
           #:example
           #:current-view
           #:test-all-examples
           #:info-stream-func
           #:reset-from-regression
           #:change-color
           #:example-callback-function
           #:compile-example-file
           #:progress-dialog
           #:create-example-listeners
           #:abort-process
           #:update-pb
           #:get-info-stream
           #:close-regression
           #:regression-testing
           #:sr
           #:test-shift-reduce
           #:ultimatum-forward
           #:test-ultimatum-forward
           #:print-operators
           #:ultimatum-soft
           #:test-ultimatum-soft
           #:cat-init
           #:cat-conds
           #:color-silver
           #:test-color-silver
           #:color-white
           #:alive-true-legs-4
           #:concept-human
           #:weight-200
           #:cat-all
           #:no-legs
           #:no-concept-legs
           #:no-weight
           #:no-concept-weight
           #:cat1
           #:color-silver1
           #:cat1n
           #:legs-2
           #:cat2
           #:color-silver2
           #:ssm
           #:ssm-color-silver
           #:*ep-per*
           #:ep-per
           #:episodic
           #:test-episodic
           #:*ep-per-replay*
           #:episodic-replay
           #:test-episodic-replay
           #:random-element
           #:random-episode
           #:random-cwdss-arguments
           #:random-cwdss-predicate
           #:vector-of-types
           #:random-episodic-predicates
           #:episodic-predicates
           #:random-episodes
           #:episodic-random
           #:init-rule
           #:rule-one
           #:test-rule-one
           #:rule-two
           #:init-rule2
           #:rule-one2
           #:rule-two2
           #:constraint
           #:ct
           #:ce
           #:cl
           #:pepb
           #:ep7i
           #:ep7e
           #:ep7e2
           #:ep7e3
           #:ep7
           #:ep72
           #:ep73
           #:ep8i
           #:ep8
           #:ep82
           #:ep82e
           #:test-eight-puzzle
           #:test-print-eight-puzzle
           #:ep83
           #:ep9i
           #:ep9
           #:ep92
           #:ep93
           #:ep102
           #:sa
           #:o1i
           #:o1e
           #:o1e2
           #:o1
           #:o12
           #:test-affine
           #:xta
           #:test-rotate-cond
           #:xtrc
           #:test-rotate-variant
           #:xtrv
           #:mt
           #:mt2
           #:ab
           #:line-detector
           #:line-detector-noise
           #:xldn
           #:smooth
           #:xs
           #:smooth2
           #:xs2
           #:smooth3
           #:xs3
           #:tetris
           #:xt
           #:filter
           #:3dmt
           #:dataset-datapaths
           #:dataset-definitions
           #:setup-dataset
           #:gdl
           #:definition
           #:simple-gdl
           #:br4
           #:sgdl
           #:ma-grid2
           #:vr
           #:vr2
           #:vr3
           #:vr4
           #:oc
           #:ev
           #:vo
           #:nd
           #:current-location
           #:assign-reward
           #:rewards7
           #:init-rl-grid7
           #:brief-init-rl-grid7
           #:rl-grid7
           #:test-rl-mb-7
           #:test-rl-dp-7
           #:test-rl-mf-7
           #:rle7
           #:rlr7
           #:rewards8
           #:test-rl-print
           #:init-rl-grid8
           #:rl-grid8
           #:test-rl-mb
           #:test-rl-dp
           #:test-rl-am
           #:test-rl-mf
           #:rle8
           #:rlr8
           #:assign-reward9
           #:init-rl-grid9
           #:brief-init-rl-grid9
           #:rle9
           #:rlr9
           #:rl-grid9
           #:test-rl-rl
           #:execute-pomdp-operator
           #:init-pomdp
           #:pomdp1-location
           #:perceive-pomdp1-location
           #:execute-pomdp1-operator
           #:random-transition-fn
           #:init-pomdp1
           #:rd1
           #:init-rw
           #:rrw
           #:test-rw-al
           #:ti
           #:tmi
           #:tma
           #:tf
           #:diachronic-location
           #:diachronic-map
           #:perceive-diachronic-object
           #:execute-diachronic-operator
           #:diachronic-slam
           #:dsl
           #:test-slam
           #:test-extend-type
           #:test-extend-type1
           #:test-extend-type2
           #:test-extend-type3
           #:define-attribute-pos
           #:pos-tagger-model
           #:train-pos-model
           #:test-pos-model
           #:train-pos-model3
           #:test-pos-model3
           #:pos-tagger-model1
           #:train-pos-model1
           #:test-pos-model1
           #:pos-tagger-model2
           #:tg
           #:tec
           #:tpm
           #:tca
           #:chunk
           #:ado
           #:ado2
           #:ado3
           #:pec
           #:tper
           #:tco
           #:tcs
           #:tmud
           #:tmud2
           #:nav
           #:tna
           #:integer-list
           #:trmi
           #:twve
           #:twvne
           #:tamuv
           #:tcoff
           #:tcwp
           #:tiuwu
           #:run-distributed-negate-single-sentence
           #:run-distributed-negate-two-sentences
           #:run-distributed-negate
           #:distributed-negate
           #:*parallel-font-colors*
           #:parallel-color-examples
           #:curr-color
           #:*parallel-exception*
           #:parallel-exception
           #:parallel-list-ex
           #:*func-file*
           #:*main-func*
           #:*parameter-list*
           #:proccnt
           #:procstr
           #:exstr
           #:cnt
           #:*mbox*
           #:current-view
           #:run-jobs
           #:parallel-info-stream-func
           #:savedat
           #:reset-from-parallel
           #:parallel-change-color
           #:parallel-callback-function
           #:compile-user-src-file
           #:parallel-progress-dialog
           #:create-parallel-listeners
           #:parallel-abort-process
           #:parallel-update-pb
           #:parallel-get-info-stream
           #:close-parallel
           #:run-parallel
           #:clone-package-system
           #:inner-bc-constants
           #:bc-plms
           #:hd-from-bc
           #:hd-from-bc-plm
           #:hd-plms
           #:bd-from-bc
           #:bd-from-bc-plm
           #:unique-dimensions-predicate
           #:all-but-agent-and-state-dimensions-plm
           #:vector-0
           #:constrain-by-0-function
           #:make-unique-argument-select
           #:make-unique-arguments-select
           #:meta-arguments
           #:meta-map
           #:npc
           #:region-function-variablep
           #:plm-piecewise-constantp
           #:update-combine-active
           #:global-summarized-predicate-plm
           #:update-global-appraisal-variables
           #:constant-equal
           #:weight-equal
           #:function-equal
           #:exponentiate-constant-times-function
           #:rank-list
           #:average-regions-in-span-recur
           #:average-regions-in-span
           #:remove-moot-slices-d
           #:remove-moot-slices-ds
           #:maximize-unique-dimensions
           #:scale-max-plm
           #:apply-attention
           #:region-cpt-entry
           #:meta-predicate-plm-to-cpt
           #:combine-open-closed-world-attention-distributions
           #:compute-global-attention-distribution
           #:global-meta-predicate-plm
           #:visual-search
           #:pimage
           #:pgoal
           #:vf-colors
           #:large-surprise
           #:vfun-colors
           #:large-goal
           #:needs
           #:mixed-world-attention
           #:read-write
	   #:sigma-menu
)
)
#+LISPWORKS (defadvice (capi::execute-with-interface-internal
               bind-*callback-interface*
               :after)
    (interface &rest other-args)
  (let* ((*callback-interface* interface))
    (sigma::add-sigma-menu)))

#+LISPWORKS (defadvice (capi::execute-with-interface
               bind-*callback-interface*
               :after)
    (interface &rest other-args)
  (let* ((*callback-interface* interface))
    (setf *package* (find-package "SIGMA"))))


