; Dialogue
(defparameter *sentences*
  '(
    (171 . "Hey sir, Chief said you wanted to see me?")
    (155 . "Can you just give me a second, here?")
    (156 . "No problem, sir.")
    (157 . "GM2, you're a San Diego guy, right?")
    (158 . "That's right.")
    (159 . "So you a Padres fan?")
    (160 . "Actually, I'm a Dodgers fan.")
    (161 . "Ah. So you're an optimist.")
    (162 . "Yeah, I know.")
    (2 . "Okay, so Chief told me you pushed GM3 Thomas.")
    (3 . "Sir, I don't know why it's me who's in here.")
    (4 . "Okay then, talk to me.")
    (5 . "It's pretty simple. You pushed Thomas. Why?")
    (6 . "Don't act like you didn't do anything wrong. YOU screwed up.")
    (7 . "Everyone's getting on my case, but I didn't start this shit. Thomas did.")
    (10 . "I understand you think Thomas is in the wrong, but you pushed him.")
    (11 . "Thomas may have pissed you off, but next time, just walk away.")
    (12 . "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")
    (13 . "Damn straight I pushed him. Sir, that guy was talking shit about my wife. You know, if you knew the whole story, you'd probably see it my way, too.")
    (15 . "Okay, Cabrillo. Tell me what went on.")
    (26 . "Cabrillo, let it go. We're here to discuss what YOU did.")
    (25 . "The more you talk, the less confidence I have in you as a supervisor.")
    (16 . "Roger that, sir. So I just got done going over duties, you know, at my work center. And all of sudden, Thomas shouts, out of nowhere, that I should go make sure my wife isn't off giving some Jody the night of his life. I told him to knock it off, but he just kept it going.")
    (167 . "So you pushed him because he was joking about you?")
    (34 . "Look, next time this happens, Chief and I will handle it. Just come get us, first.")
    (46 . "People piss me off all the time. But you don't see me pushing anybody, do you?")
    (168 . "You bet.")
    (169 . "Look, I know that's not cool, but do you think pushing him was the right decision?")
    (170 . "I gave him a chance to stop, but he didn't.")
    (17 . "Cabrillo, you're a supervisor. You need to set the right example.")
    (22 . "I get that, sir. But what the hell do you do when a guy acts like that?")
    (23 . "Did you think about what would happen if you pushed him?")
    (47 . "Well, pushing him definitely wasn't the right answer.")
    (48 . "That's what the command structure is for. You don't know that by now?")
    (163 . "No.")
    (164 . "You gotta think about how your actions affect not only you, but also your work center.")
    (27 . "Yeah, I know.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (122 . "Well, Chief and I will work with you to make sure this doesn't happen again. Okay?")
    (86 . "Damn straight. So what should I do with you?")
    (35 . "Man, I dunno. I guess things started to change, like, a few months ago. He got passed up after screwing up on his exam. Then I got frocked. And when I talked to him about it, things were cool.")
    (36 . "So you guys aren't friends anymore?")
    (50 . "Well, it all makes sense now. Chief and I will keep an eye on things.")
    (51 . "So why didn't you think about this before you got into it with him?")
    (37 . "I don't have a problem with Thomas, but apparently he's got something against me.")
    (38 . "Do we need to get Thomas up here later to fix this?")
    (124 . "I see. Well, I know you got what it takes to work through this situation.")
    (125 . "Well, things have a way of working themselves out.")
    (128 . "That's fine with me.")
    (165 . "Okay, well, is there anything else you want to tell me about this?")
    (130 . "Fair enough. Then let's get him up here when we're done.")
    (132 . "I'll think about it. For now, just get back to work.")
    (166 . "Nah, I think that's it.")
    (129 . "All right. To be fair about this, I'm going to have the same conversation with Thomas I just had with you.")
    (39 . "Roger that, sir.")
    (40 . "So remember: be a leader and set the right example.")
    (52 . "Okay, so what do you think is a fair reprimand for you in this situation?")
    (53 . "Okay, good. You're dismissed.")
    (56 . "Okay, it won't happen again.")
    (57 . "All right. Let's go ahead and fill out a counseling sheet so we can learn from this.")
    (58 . "I'm glad you understand. So consider this a warning not to do it again.")
    (59 . "Well, I'm just glad you get it. Go ahead and get back to work.")
    (60 . "Yes, sir.")
    (61 . "Yes, sir.")
    (62 . "Yes, sir.")
    (55 . "I don't know, sir. I mean, you're probably thinking about a counseling sheet, but you could let me off with a warning, I guess. That seems fair.")
    (63 . "Just what I was thinking. We should fill out a counseling sheet.")
    (65 . "A warning will suffice. Just don't let this happen again.")
    (66 . "I think you get what you need to do. Just get back to work, okay?")
    (64 . "Yes, sir.")
    (67 . "Yes, sir.")
    (68 . "Yes, sir.")
    (54 . "Yes, sir.")
    (131 . "Sounds good, sir.")
    (80 . "Good. So let's fill out a counseling sheet so we can learn from all this.")
    (81 . "Well, so consider this a warning. Try not to go around pushing people anymore.")
    (82 . "Good. Now get out of here.")
    (83 . "Yes, sir.")
    (84 . "Yes, sir.")
    (85 . "Yes, sir.")
    (133 . "Yes, sir.")
    (126 . "I guess.")
    (40 . "So remember: be a leader and set the right example.")
    (52 . "Okay, so what do you think is a fair reprimand for you in this situation?")
    (53 . "Okay, good. You're dismissed.")
    (134 . "Sir, it's not like I planned to push him. I got pissed and, and reacted.")
    (135 . "I suppose you're right. Okay, so will this be a problem anymore?")
    (137 . "Well, then, think before you react next time.")
    (138 . "And look where you are now. All right, get back to work while I think about all this.")
    (136 . "I mean, I'm not gonna push anybody again, if that's what you mean. But, I'm pretty sure Thomas isn't going to be over this.")
    (129 . "All right. To be fair about this, I'm going to have the same conversation with Thomas I just had with you.")
    (130 . "Fair enough. Then let's get him up here when we're done.")
    (132 . "I'll think about it. For now, just get back to work.")
    (139 . "Yes, sir.")
    (80 . "Good. So let's fill out a counseling sheet so we can learn from all this.")
    (81 . "Well, so consider this a warning. Try not to go around pushing people anymore.")
    (82 . "Good. Now get out of here.")
    (140 . "Yes, sir.")
    (123 . "Yes, sir.")
    (40 . "So remember: be a leader and set the right example.")
    (52 . "Okay, so what do you think is a fair reprimand for you in this situation?")
    (53 . "Okay, good. You're dismissed.")
    (87 . "Well, you could let me off with a warning, I guess.")
    (88 . "Let's fill out a counseling sheet so we can track your progress.")
    (89 . "Sounds fair. So consider this your one and only warning. No pushing people.")
    (90 . "Actually, I think you get the point. Just get back to work.")
    (91 . "Yes, sir.")
    (92 . "Yes, sir.")
    (93 . "Yes, sir.")
    (49 . "I know, sir. It won't happen again.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (78 . "Okay, well, Chief and I will work with you to fix this situation, okay?")
    (86 . "Damn straight. So what should I do with you?")
    (79 . "Yeah, I guess I get it.")
    (80 . "Good. So let's fill out a counseling sheet so we can learn from all this.")
    (81 . "Well, so consider this a warning. Try not to go around pushing people anymore.")
    (82 . "Good. Now get out of here.")
    (106 . "Of course, sir. I guess that means I should use it next time.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (107 . "That's right. But Chief and I will work with you to make sure this doesn't happen again, okay?")
    (108 . "That's right. So get back to work and come to us if you need help.")
    (109 . "Yes, sir.")
    (69 . "But sir, it's totally different. Thomas and I are practically rack mates.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (70 . "In that case, Chief and I will just have to keep an eye on things, okay?")
    (71 . "Then you should know how he is. Even I know Thomas is a smart ass.")
    (110 . "Exactly! How do you supervise that?")
    (111 . "You're in a position to lead now. Do the right thing and people will respect you for it.")
    (112 . "Well, you're a smart guy. You'll figure it out.")
    (113 . "Then maybe you're in the wrong job. Now get out of here while I try to figure out what to do with you.")
    (127 . "Yes, sir.")
    (24 . "Okay, I get it.")
    (29 . "Look, part of your job now is to set the example out there. Got it?")
    (30 . "Hold up. What's the deal with you and Thomas anyway?")
    (46 . "People piss me off all the time. But you don't see me pushing anybody, do you?")
    (141 . "How I act won't change the fact that Thomas is still gonna be an asshole.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (142 . "Look, if you fix your behavior, it won't matter if Thomas is giving you hell.")
    (143 . "I'll talk to Thomas to figure that out. In the meantime, you worry about yourself.")
    (144 . "I understand, but can we at least talk about what's going on with Thomas?")
    (38 . "Do we need to get Thomas up here later to fix this?")
    (146 . "Be the bigger man. Then it won't matter what Thomas does.")
    (147 . "Get over it, already. Now get back out there and do your job.")
    (148 . "Fine.")
    (145 . "Does that mean you're gonna write me up?")
    (149 . "Yeah, it does. You need to learn from this, Cabrillo. So let's fill out this counseling sheet.")
    (151 . "No, but consider this your one and only warning.")
    (153 . "No, I think I'll let you off this time. You better have learned your lesson.")
    (150 . "Yes, sir.")
    (152 . "Yes, sir.")
    (154 . "Yes, sir.")
    (31 . "You have to be kidding me. Sir, what the hell do you expect me to do when a guy acts like that?")
    (32 . "Try to diffuse the situation first. If that doesn't work, come to me or Chief. Got it?")
    (72 . "Like I said, either deal with it the right way, or just walk away.")
    (73 . "Check your attitude, Cabrillo, or this is going up to higher.")
    (33 . "Got it, sir.")
    (28 . "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
    (41 . "Fair enough. Just make sure you stay calm out there from now on.")
    (42 . "Okay, good. Now get get back to work while I figure out what to do about all this.")
    (44 . "But what happens the next time he gives me crap? I mean, I'm his supervisor. That's not supposed to happen.")
    (45 . "Use the chain of command. If you're not able to get him to back off, Chief or I will handle it.")
    (1 . "I'm sure you'll figure it out, Cabrillo. Just don't push him next time.")
    (76 . "Stop worrying about him. Now get out there and get back to work.")
    (77 . "Yes, sir.")
    (43 . "Yes, sir.")
    (74 . "Fine, sir. But what about Thomas?")
    (45 . "Use the chain of command. If you're not able to get him to back off, Chief or I will handle it.")
    (75 . "Just do your job and keep your cool, and it'll be fine.")
    (76 . "Stop worrying about him. Now get out there and get back to work.")
    (114 . "Yes, sir.")
    (116 . "Okay, so let's fill out a counseling sheet so we can learn and move on from this.")
    (117 . "All right. Consider this a warning, so don't let this kind of thing happen again.")
    (118 . "Good. You're dismissed.")
    (119 . "Yes, sir. PREVIOUS")
    (120 . "Yes, sir.")
    (121 . "Yes, sir.")
    (94 . "What's the point? I don't even know what's going on, anymore.")
    (95 . "Bottom line, Cabrillo. Do your job and keep your composure and this will all blow over.")
    (96 . "It's simple. You're here because you screwed up, and we're trying to fix the problem.")
    (97 . "I don't have time to deal with this nonsense. I'll see you at Captain's Mast.")
    (115 . "I guess, sir.")
    (116 . "Okay, so let's fill out a counseling sheet so we can learn and move on from this.")
    (117 . "All right. Consider this a warning, so don't let this kind of thing happen again.")
    (118 . "Good. You're dismissed.")
    (99 . "So how are we gonna \"fix the problem\"?")
    (100 . "We're going to fill out a counseling sheet so you can hopefully learn from this.")
    (101 . "Let me put it this way: this is your one and ONLY warning.")
    (102 . "Thanks to your attitude, this is going up to Captain's Mast. That should fix it.")
    (105 . "Yes, sir.")
    (104 . "Okay, sir. Whatever you say.")
    (103 . "Yes, sir.")
    (98 . "Yes, sir.")
    (14 . "I can't believe this. You know what, sir? I get it. I shouldn't have pushed him. But I'm sorry, walking away was not an option.")
    (17 . "Cabrillo, you're a supervisor. You need to set the right example.")
    (18 . "Too bad. When you take on more responsibility, you have to do things that aren't easy.")
    (25 . "The more you talk, the less confidence I have in you as a supervisor.")
    (19 . "What's the point? I'm screwed, and Thomas isn't. This is such BULLSHIT.")
    (172 . "Cabrillo, you're his supervisor. You can't just push him around, no matter what he does.")
    (173 . "Cabrillo, chill out. We're not gonna throw you overboard. But get this into your head: you can't be pushing people.")
    (20 . "This is how you want to play it? Fine. Congratulations, this is going up to Captain's Mast.")
    (178 . "I get that, sir. But what the hell do you do when a guy acts like that?")
    (23 . "Did you think about what would happen if you pushed him?")
    (47 . "Well, pushing him definitely wasn't the right answer.")
    (48 . "That's what the command structure is for. You don't know that by now?")
    (179 . "Okay, I get it.")
    (29 . "Look, part of your job now is to set the example out there. Got it?")
    (30 . "Hold up. What's the deal with you and Thomas anyway?")
    (46 . "People piss me off all the time. But you don't see me pushing anybody, do you?")
    (21 . "Pfft. Whatever.")
    (8 . "He deserved it. If he didn't start talking trash about my wife, none of this shit would've happened.")
    (10 . "I understand you think Thomas is in the wrong, but you pushed him.")
    (11 . "Thomas may have pissed you off, but next time, just walk away.")
    (12 . "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")
    (9 . "Me? Me? Awesome, sir. I get it. It's cool with you for someone to diss another guy's wife.")
    (174 . "I understand you think Thomas is in the wrong, but you pushed him.")
    (176 . "Thomas may have pissed you off, but next time, just walk away.")
    (12 . "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")
    (175 . "Damn straight I pushed him. Sir, that guy was talking shit about my wife. You know, if you knew the whole story, you'd probably see it my way, too.")
    (15 . "Okay, Cabrillo. Tell me what went on.")
    (26 . "Cabrillo, let it go. We're here to discuss what YOU did.")
    (25 . "The more you talk, the less confidence I have in you as a supervisor.")
    (177 . "I can't believe this. You know what, sir? I get it. I shouldn't have pushed him. But I'm sorry, walking away was not an option.")
    (17 . "Cabrillo, you're a supervisor. You need to set the right example.")
    (18 . "Too bad. When you take on more responsibility, you have to do things that aren't easy.")
    (25 . "The more you talk, the less confidence I have in you as a supervisor.")))

(defparameter *answers*
    '(
      (0 . (155))
      (155 . (157))
      (157 . (159))
      (159 . (161))
      (161 . (2))
      (2 . (4 5 6))
      (4 . (10 11 12))
      (10 . (15 26 25))
      (15 . (167 34 46))
      (167 . (169))
      (169 . (17))
      (17 . (23 47 48))
      (23 . (164))
      (34 . (28 122 86))
      (164 . (28 122 86))
      (28 . (36 50 51))
      (30 . (36 50 51))
      (36 . (38 124 125))
      (38 . (165 130 132))
      (165 . (129))
      (45 . (40 52 53))
      (50 . (40 52 53))
      (70 . (40 52 53))
      (129 . (40 52 53))
      (1 . (57 58 59))
      (40 . (57 58 59))
      (124 . (57 58 59))
      (52 . (63 65 66))
      (130 . (80 81 82))
      (125 . (40 52 53))
      (51 . (135 137 138))
      (135 . (129 130 132))
      (137 . (80 81 82))
      (122 . (40 52 53))
      (86 . (88 89 90))
      (47 . (28 78 86))
      (78 . (80 81 82)) (107 . (80 81 82)) (111 . (80 81 82)) (112 . (80 81 82)) (146 . (80 81 82))
      (48 . (28 107 108))
      (46 . (28 70 71))
      (71 . (111 112 113))
      (18 . (29 30 46)) (26 . (29 30 46))
      (29 . (28 142 143))
      (142 . (38 146 147))
      (143 . (149 151 153))
      (25 . (32 72 73))
      (32 . (28 41 42))
      (41 . (45 1 76))
      (72 . (45 75 76))
      (75 . (116 117 118))
      (73 . (95 96 97))
      (95 . (116 117 118))
      (96 . (100 101 102))
      (11 . (17 18 25))
      (12 . (172 173 20))
      (172 . (23 47 48))
      (173 . (29 30 46))
      (5 . (10 11 12))
      (6 . (174 176 12))
      (174 . (15 26 25))
      (176 . (17 18 25))
      ;previous -> possible responses
      ))

(defun print-out-legal-transitions ()
  (dolist (transition *answers*)
    (let ((state (car transition))
          (next (cdr transition)))
      (dolist (next-state next)
        (format t "(1 ~a ~a)~%" state next-state)))))

(defun print-out-adding-answers ()
  (dolist (transition *answers*)
    (let ((next (cdr transition)))
      (dolist (next-state next)
        (let ((sentence (cdr (assoc next-state *sentences*))))
          (format t "(add-new-sentence ~a \"~a\")~%" next-state sentence))))))

(defun delimiterp (c) (position c " ,.;/?!()&:"))

(defun my-split (string)
  (loop :for beg = (position-if-not #'delimiterp string)
    :then (position-if-not #'delimiterp string :start (1+ end))
    :for end = (and beg (position-if #'delimiterp string :start beg))
    :when beg :collect (subseq string beg end)
    :while end))

(defun execute-one-decision()
  (wsd-model)
  (format t "Please enter your sentence in one line:~%")
  (let ((sentence (read-line)))
    
    (let ((processed-sentence (map 'string #'(lambda (c) (cond ((CHAR= c #\') #\_) (t c))) sentence)))
      (let ((processed-words (mapcar #'string-downcase (my-split processed-sentence))))
        (dolist (word processed-words)
          (cond ((member word existing-words :test #'string=)
                 (let ((word-symbol (intern (string-upcase (concatenate 'string "WORD-" word)))))
                   (perceive `((,word-symbol (,word-symbol T)))))))
          )
        (d 1)
        (ppwm 'sentence-prior 'array)))))

(defun recognize-sentence (sentence)
    (let ((processed-sentence (map 'string #'(lambda (c) (cond ((CHAR= c #\') #\_) (t c))) sentence)))
      (let ((processed-words (mapcar #'string-downcase (my-split processed-sentence))))
        ; Halt dialog on goodbye
        (when (string= (car processed-words) "goodbye")
          (halt)
          (format t "Goodbye.")
          )
        (dolist (word processed-words)
          (cond ((member word existing-words :test #'string=)
                 (let ((word-symbol (intern (string-upcase (concatenate 'string "WORD-" word)))))
                   (perceive `((,word-symbol (,word-symbol T)))))))
          )
        )))

(defun show-result ()
  (ppwm 'sentence-prior 'array))

(defparameter existing-words
  ()
)

(defparameter existing-conditional ())
(defparameter existing-sentences ())

(defparameter word-sentence ())

(defun write-out-conditionals ()
  (dolist (word-sentence-item word-sentence)
    (let ((function-list ()) (existing-sentences ()))
      (dolist (sentence (cdr word-sentence-item))
        (cond ((not (member sentence existing-sentences))
               (setf function-list (cons `(0.9 ,sentence T) function-list))
               (setf function-list (cons `(0.1 ,sentence F) function-list))
               (setf existing-sentences (cons sentence existing-sentences)))))
      (setf function-list (cons '(1 * *) function-list))
      (let ((word (car word-sentence-item)))
        (let ((word-symbol (intern (string-upcase (concatenate 'string "WORD-" word)))))
          (let ((concatenated (concatenate 'string "conditional-word-" word)))
            (conditional (intern (string-upcase concatenated))
                         :condacts '((SENTENCE-PRIOR (MEANING (M))))
                         :conditions `((,word-symbol (,word-symbol (,word-symbol)))
                                       )
                         :FUNCTION-VARIABLE-NAMES `(M ,word-symbol)
                         :NORMAL word-symbol
                         :FUNCTION function-list
                         ))))
      ;debug use (format t "~a~%" function-list)
      ))
  )

(defun print-elements-of-list (list)
  "Print each element of LIST on a line of its own."
  (print (car list))
  (cond ((cdr list)
         (print-elements-of-list (cdr list)))))



(defun add-new-sentence (sentence-number sentence)
  (setf existing-conditional ())
  ;(format t "Adding new sentence ~a: ~a~%" sentence-number sentence) ;debug
  (cond ((not (member sentence-number existing-sentences))
         (let ((processed-sentence (map 'string #'(lambda (c) (cond ((CHAR= c #\') #\_) (t c))) sentence)))
           (let ((processed-words (mapcar #'string-downcase (my-split processed-sentence))))
             (dolist (word processed-words)
               (let ((word-sentence-item (assoc word word-sentence :test #'string=)))
                 
                 (cond (word-sentence-item
                        (setf (cdr word-sentence-item) (cons sentence-number (cdr word-sentence-item)))
                        )
                       (t
                        (setf word-sentence (cons (list word sentence-number) word-sentence))
                        ))
                 )
               ;(format t "Existing words: ~a~%" existing-words) ;debug
               (cond ((not (member word existing-words :test #'string=))
                      (setf existing-words (cons word existing-words))
                      ;(format t "Existing-words 2: ~a~%" existing-words) ;debug
                      (let ((word-symbol (intern (string-upcase (concatenate 'string "WORD-" word)))))
                        (predicate word-symbol :WORLD 'OPEN :UNIQUE (list word-symbol) :PERCEPTION T :ARGUMENTS `((,word-symbol BOOL %)))
                        )))
               (let ((word-symbol (intern (string-upcase (concatenate 'string "WORD-" word)))))
            
                 (cond ((not (member word existing-conditional :test #'string=))

                        (setf existing-conditional (cons word existing-conditional))))
                 (setf existing-sentences (cons sentence-number existing-sentences))
                 )))))
        ;debug use (t
         ;(format t "~a: ~a already exists.~%" sentence-number sentence))
        )
)
;this function creates the model
(defun wsd-model()
  (new-type 'bool :constants '(t f))
  
  (setf existing-words ())
  (setf existing-sentences ())

;we are trying to decide the meaning of the sentence- there are three alternatives:meaning1, meaning2, and meaning3
  (PREDICATE 'SENTENCE-PRIOR :WORLD 'open :UNIQUE '(MEANING) :PERCEPTION T :ARGUMENTS '((MEANING sentence-number %)))

  (predicate 'sentence-selection :world 'closed :arguments '((chosen-sentence sentence-number !)))

  (add-new-sentence 155 "Can you just give me a second, here?")
  (add-new-sentence 157 "GM2, you're a San Diego guy, right?")
  (add-new-sentence 159 "So you a Padres fan?")
  (add-new-sentence 161 "Ah. So you're an optimist.")
  (add-new-sentence 2 "Okay, so Chief told me you pushed GM3 Thomas.")
  (add-new-sentence 4 "Okay then, talk to me.")
  (add-new-sentence 5 "It's pretty simple. You pushed Thomas. Why?")
  (add-new-sentence 6 "Don't act like you didn't do anything wrong. YOU screwed up.")
  (add-new-sentence 10 "I understand you think Thomas is in the wrong, but you pushed him.")
  (add-new-sentence 11 "Thomas may have pissed you off, but next time, just walk away.")
  (add-new-sentence 12 "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")

  (add-new-sentence 15 "Okay, Cabrillo. Tell me what went on.")
  (add-new-sentence 26 "Cabrillo, let it go. We're here to discuss what YOU did.")
  (add-new-sentence 25 "The more you talk, the less confidence I have in you as a supervisor.")
  (add-new-sentence 167 "So you pushed him because he was joking about you?")
  (add-new-sentence 34 "Look, next time this happens, Chief and I will handle it. Just come get us, first.")
  (add-new-sentence 46 "People piss me off all the time. But you don't see me pushing anybody, do you?")
  (add-new-sentence 169 "Look, I know that's not cool, but do you think pushing him was the right decision?")
  (add-new-sentence 17 "Cabrillo, you're a supervisor. You need to set the right example.")
  (add-new-sentence 23 "Did you think about what would happen if you pushed him?")
  (add-new-sentence 47 "Well, pushing him definitely wasn't the right answer.")
  (add-new-sentence 48 "That's what the command structure is for. You don't know that by now?")
  (add-new-sentence 164 "You gotta think about how your actions affect not only you, but also your work center.")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 122 "Well, Chief and I will work with you to make sure this doesn't happen again. Okay?")
  (add-new-sentence 86 "Damn straight. So what should I do with you?")
  
  (add-new-sentence 36 "So you guys aren't friends anymore?")
  (add-new-sentence 50 "Well, it all makes sense now. Chief and I will keep an eye on things.")
  (add-new-sentence 51 "So why didn't you think about this before you got into it with him?")
  
  (add-new-sentence 38 "Do we need to get Thomas up here later to fix this?")
  (add-new-sentence 124 "I see. Well, I know you got what it takes to work through this situation.")
  (add-new-sentence 125 "Well, things have a way of working themselves out.")
  (add-new-sentence 165 "Okay, well, is there anything else you want to tell me about this?")
  (add-new-sentence 130 "Fair enough. Then let's get him up here when we're done.")
  (add-new-sentence 132 "I'll think about it. For now, just get back to work.")
  (add-new-sentence 129 "All right. To be fair about this, I'm going to have the same conversation with Thomas I just had with you.")
  (add-new-sentence 40 "So remember: be a leader and set the right example.")
  (add-new-sentence 52 "Okay, so what do you think is a fair reprimand for you in this situation?")
  (add-new-sentence 53 "Okay, good. You're dismissed.")
  
  (add-new-sentence 57 "All right. Let's go ahead and fill out a counseling sheet so we can learn from this.")
  (add-new-sentence 58 "I'm glad you understand. So consider this a warning not to do it again.")
  (add-new-sentence 59 "Well, I'm just glad you get it. Go ahead and get back to work.")
  
  (add-new-sentence 63 "Just what I was thinking. We should fill out a counseling sheet.")
  (add-new-sentence 65 "A warning will suffice. Just don't let this happen again.")
  (add-new-sentence 66 "I think you get what you need to do. Just get back to work, okay?")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 40 "So remember: be a leader and set the right example.")
  (add-new-sentence 52 "Okay, so what do you think is a fair reprimand for you in this situation?")
  (add-new-sentence 53 "Okay, good. You're dismissed.")
  (add-new-sentence 135 "I suppose you're right. Okay, so will this be a problem anymore?")
  (add-new-sentence 137 "Well, then, think before you react next time.")
  (add-new-sentence 138 "And look where you are now. All right, get back to work while I think about all this.")
  (add-new-sentence 129 "All right. To be fair about this, I'm going to have the same conversation with Thomas I just had with you.")
  (add-new-sentence 130 "Fair enough. Then let's get him up here when we're done.")
  (add-new-sentence 132 "I'll think about it. For now, just get back to work.")
  
  (add-new-sentence 88 "Let's fill out a counseling sheet so we can track your progress.")
  (add-new-sentence 89 "Sounds fair. So consider this your one and only warning. No pushing people.")
  (add-new-sentence 90 "Actually, I think you get the point. Just get back to work.")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 78 "Okay, well, Chief and I will work with you to fix this situation, okay?")
  (add-new-sentence 86 "Damn straight. So what should I do with you?")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 80 "Good. So let's fill out a counseling sheet so we can learn from all this.")
  (add-new-sentence 81 "Well, so consider this a warning. Try not to go around pushing people anymore.")
  (add-new-sentence 82 "Good. Now get out of here.")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 107 "That's right. But Chief and I will work with you to make sure this doesn't happen again, okay?")
  (add-new-sentence 108 "That's right. So get back to work and come to us if you need help.")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 70 "In that case, Chief and I will just have to keep an eye on things, okay?")
  (add-new-sentence 71 "Then you should know how he is. Even I know Thomas is a smart ass.")
  (add-new-sentence 111 "You're in a position to lead now. Do the right thing and people will respect you for it.")
  (add-new-sentence 112 "Well, you're a smart guy. You'll figure it out.")
  (add-new-sentence 113 "Then maybe you're in the wrong job. Now get out of here while I try to figure out what to do with you.")
  (add-new-sentence 29 "Look, part of your job now is to set the example out there. Got it?")
  (add-new-sentence 30 "Hold up. What's the deal with you and Thomas anyway?")
  (add-new-sentence 46 "People piss me off all the time. But you don't see me pushing anybody, do you?")
  (add-new-sentence 29 "Look, part of your job now is to set the example out there. Got it?")
  (add-new-sentence 30 "Hold up. What's the deal with you and Thomas anyway?")
  (add-new-sentence 46 "People piss me off all the time. But you don't see me pushing anybody, do you?")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 142 "Look, if you fix your behavior, it won't matter if Thomas is giving you hell.")
  (add-new-sentence 143 "I'll talk to Thomas to figure that out. In the meantime, you worry about yourself.")
  (add-new-sentence 38 "Do we need to get Thomas up here later to fix this?")
  (add-new-sentence 146 "Be the bigger man. Then it won't matter what Thomas does.")
  (add-new-sentence 147 "Get over it, already. Now get back out there and do your job.")
  (add-new-sentence 149 "Yeah, it does. You need to learn from this, Cabrillo. So let's fill out this counseling sheet.")
  (add-new-sentence 151 "No, but consider this your one and only warning.")
  (add-new-sentence 153 "No, I think I'll let you off this time. You better have learned your lesson.")
  (add-new-sentence 32 "Try to diffuse the situation first. If that doesn't work, come to me or Chief. Got it?")
  (add-new-sentence 72 "Like I said, either deal with it the right way, or just walk away.")
  (add-new-sentence 73 "Check your attitude, Cabrillo, or this is going up to higher.")
  (add-new-sentence 28 "Cabrillo, I'm curious--Chief thought you guys were buds. What's up?")
  (add-new-sentence 41 "Fair enough. Just make sure you stay calm out there from now on.")
  (add-new-sentence 42 "Okay, good. Now get get back to work while I figure out what to do about all this.")
  (add-new-sentence 45 "Use the chain of command. If you're not able to get him to back off, Chief or I will handle it.")
  (add-new-sentence 1 "I'm sure you'll figure it out, Cabrillo. Just don't push him next time.")
  (add-new-sentence 76 "Stop worrying about him. Now get out there and get back to work.")
  (add-new-sentence 45 "Use the chain of command. If you're not able to get him to back off, Chief or I will handle it.")
  (add-new-sentence 75 "Just do your job and keep your cool, and it'll be fine.")
  (add-new-sentence 76 "Stop worrying about him. Now get out there and get back to work.")
  (add-new-sentence 116 "Okay, so let's fill out a counseling sheet so we can learn and move on from this.")
  (add-new-sentence 117 "All right. Consider this a warning, so don't let this kind of thing happen again.")
  (add-new-sentence 118 "Good. You're dismissed.")
  (add-new-sentence 95 "Bottom line, Cabrillo. Do your job and keep your composure and this will all blow over.")
  (add-new-sentence 96 "It's simple. You're here because you screwed up, and we're trying to fix the problem.")
  (add-new-sentence 97 "I don't have time to deal with this nonsense. I'll see you at Captain's Mast.")
  (add-new-sentence 116 "Okay, so let's fill out a counseling sheet so we can learn and move on from this.")
  (add-new-sentence 117 "All right. Consider this a warning, so don't let this kind of thing happen again.")
  (add-new-sentence 118 "Good. You're dismissed.")
  (add-new-sentence 100 "We're going to fill out a counseling sheet so you can hopefully learn from this.")
  (add-new-sentence 101 "Let me put it this way: this is your one and ONLY warning.")
  (add-new-sentence 102 "Thanks to your attitude, this is going up to Captain's Mast. That should fix it.")
  (add-new-sentence 17 "Cabrillo, you're a supervisor. You need to set the right example.")
  (add-new-sentence 18 "Too bad. When you take on more responsibility, you have to do things that aren't easy.")
  (add-new-sentence 25 "The more you talk, the less confidence I have in you as a supervisor.")
  (add-new-sentence 172 "Cabrillo, you're his supervisor. You can't just push him around, no matter what he does.")
  (add-new-sentence 173 "Cabrillo, chill out. We're not gonna throw you overboard. But get this into your head: you can't be pushing people.")
  (add-new-sentence 20 "This is how you want to play it? Fine. Congratulations, this is going up to Captain's Mast.")
  (add-new-sentence 23 "Did you think about what would happen if you pushed him?")
  (add-new-sentence 47 "Well, pushing him definitely wasn't the right answer.")
  (add-new-sentence 48 "That's what the command structure is for. You don't know that by now?")
  (add-new-sentence 29 "Look, part of your job now is to set the example out there. Got it?")
  (add-new-sentence 30 "Hold up. What's the deal with you and Thomas anyway?")
  (add-new-sentence 46 "People piss me off all the time. But you don't see me pushing anybody, do you?")
  (add-new-sentence 10 "I understand you think Thomas is in the wrong, but you pushed him.")
  (add-new-sentence 11 "Thomas may have pissed you off, but next time, just walk away.")
  (add-new-sentence 12 "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")
  (add-new-sentence 174 "I understand you think Thomas is in the wrong, but you pushed him.")
  (add-new-sentence 176 "Thomas may have pissed you off, but next time, just walk away.")
  (add-new-sentence 12 "Hey GM2. That's the kind of attitude that'll get you sent up to higher.")
  (add-new-sentence 15 "Okay, Cabrillo. Tell me what went on.")
  (add-new-sentence 26 "Cabrillo, let it go. We're here to discuss what YOU did.")
  (add-new-sentence 25 "The more you talk, the less confidence I have in you as a supervisor.")
  (add-new-sentence 17 "Cabrillo, you're a supervisor. You need to set the right example.")
  (add-new-sentence 18 "Too bad. When you take on more responsibility, you have to do things that aren't easy.")
  (add-new-sentence 25 "The more you talk, the less confidence I have in you as a supervisor.")
  
;this conditional sets the prior distribution on sentence meaning
  (CONDITIONAL 'PRIOR-MEANING
               :CONDACTS '((SENTENCE-PRIOR (MEANING (M))))
               :conditions '((dialog-state (state 0) (state-number (state-number))))
               :FUNCTION-VARIABLE-NAMES '(state-number M)
               :NORMAL 'M
               :FUNCTION '((1 0 155)
                           (1 155 157)
                           (1 157 159)
                           (1 159 161)
                           (1 161 2)
                           (1 2 4)
                           (1 2 5)
                           (1 2 6)
                           (1 4 10)
                           (1 4 11)
                           (1 4 12)
                           (1 10 15)
                           (1 10 26)
                           (1 10 25)
                           (1 15 167)
                           (1 15 34)
                           (1 15 46)
                           (1 167 169)
                           (1 169 17)
                           (1 17 23)
                           (1 17 47)
                           (1 17 48)
                           (1 23 164)
                           (1 34 28)
                           (1 34 122)
                           (1 34 86)
                           (1 164 28)
                           (1 164 122)
                           (1 164 86)
                           (1 28 36)
                           (1 28 50)
                           (1 28 51)
                           (1 30 36)
                           (1 30 50)
                           (1 30 51)
                           (1 36 38)
                           (1 36 124)
                           (1 36 125)
                           (1 38 165)
                           (1 38 130)
                           (1 38 132)
                           (1 165 129)
                           (1 45 40)
                           (1 45 52)
                           (1 45 53)
                           (1 50 40)
                           (1 50 52)
                           (1 50 53)
                           (1 70 40)
                           (1 70 52)
                           (1 70 53)
                           (1 129 40)
                           (1 129 52)
                           (1 129 53)
                           (1 1 57)
                           (1 1 58)
                           (1 1 59)
                           (1 40 57)
                           (1 40 58)
                           (1 40 59)
                           (1 124 57)
                           (1 124 58)
                           (1 124 59)
                           (1 52 63)
                           (1 52 65)
                           (1 52 66)
                           (1 130 80)
                           (1 130 81)
                           (1 130 82)
                           (1 125 40)
                           (1 125 52)
                           (1 125 53)
                           (1 51 135)
                           (1 51 137)
                           (1 51 138)
                           (1 135 129)
                           (1 135 130)
                           (1 135 132)
                           (1 137 80)
                           (1 137 81)
                           (1 137 82)
                           (1 122 40)
                           (1 122 52)
                           (1 122 53)
                           (1 86 88)
                           (1 86 89)
                           (1 86 90)
                           (1 47 28)
                           (1 47 78)
                           (1 47 86)
                           (1 78 80)
                           (1 78 81)
                           (1 78 82)
                           (1 107 80)
                           (1 107 81)
                           (1 107 82)
                           (1 111 80)
                           (1 111 81)
                           (1 111 82)
                           (1 112 80)
                           (1 112 81)
                           (1 112 82)
                           (1 146 80)
                           (1 146 81)
                           (1 146 82)
                           (1 48 28)
                           (1 48 107)
                           (1 48 108)
                           (1 46 28)
                           (1 46 70)
                           (1 46 71)
                           (1 71 111)
                           (1 71 112)
                           (1 71 113)
                           (1 18 29)
                           (1 18 30)
                           (1 18 46)
                           (1 26 29)
                           (1 26 30)
                           (1 26 46)
                           (1 29 28)
                           (1 29 142)
                           (1 29 143)
                           (1 142 38)
                           (1 142 146)
                           (1 142 147)
                           (1 143 149)
                           (1 143 151)
                           (1 143 153)
                           (1 25 32)
                           (1 25 72)
                           (1 25 73)
                           (1 32 28)
                           (1 32 41)
                           (1 32 42)
                           (1 41 45)
                           (1 41 1)
                           (1 41 76)
                           (1 72 45)
                           (1 72 75)
                           (1 72 76)
                           (1 75 116)
                           (1 75 117)
                           (1 75 118)
                           (1 73 95)
                           (1 73 96)
                           (1 73 97)
                           (1 95 116)
                           (1 95 117)
                           (1 95 118)
                           (1 96 100)
                           (1 96 101)
                           (1 96 102)
                           (1 11 17)
                           (1 11 18)
                           (1 11 25)
                           (1 12 172)
                           (1 12 173)
                           (1 12 20)
                           (1 172 23)
                           (1 172 47)
                           (1 172 48)
                           (1 173 29)
                           (1 173 30)
                           (1 173 46)
                           (1 5 10)
                           (1 5 11)
                           (1 5 12)
                           (1 6 174)
                           (1 6 176)
                           (1 6 12)
                           (1 174 15)
                           (1 174 26)
                           (1 174 25)
                           (1 176 17)
                           (1 176 18)
                           (1 176 25))
               )
  (predicate 'current-state :world 'closed :arguments '((current-state sentence-number !)))

  (conditional 'selecting-sentence
               :conditions '((sentence-prior (meaning (sentence))))
               :actions '((sentence-selection (chosen-sentence (sentence)))))

  (conditional 'cannot-select
               :actions '((sentence-selection (chosen-sentence (sentence))))
               :function-variable-names '(sentence)
               :function '((0.5 0)))
  ;debug use (format t "wsd-model has finished")
  ()
)

;this function perceives a sample sentence
(defun perceive-sample-sentence (sentence)
  (let ((words (my-split sentence)))
    (format t "~a" words)))

(defparameter waited-for-one-turn nil)

(defun show-response (state-number)
  (let ((sentence (cdr (assoc state-number *sentences*))))
    (format nil "~a: ~a" state-number sentence)))

(defun dialog ()
  (init)
  (setq trace-decisions nil)
  (setq waited-for-one-turn nil)
  (setq existing-words nil)
  
  (setq existing-conditional nil)
  (setq existing-sentences nil)
  
  (setq word-sentence nil)

  (new-type 'sentence-number :numeric t :discrete t :max 200 :min 0)
  
  (init-operators 'symbols '(listen speak))

  (setq pre-d '())
  (setq post-d '((let ((speak-sentence (nonstate-value 'speak-sentence))
                       (op (operator-in-state  0)))
                       (let ((sentence (cdr (assoc speak-sentence *sentences*))))
                         (cond
                          (waited-for-one-turn
                           ; Print distribution over candidate sentences if haven't said goodbye
                           (when (not (haltp))
                             (format t "Distribution over the sentences: ")
                             (ppvn 'sentence-prior)
                             (format t "~&")
                             )
                           (let ((heard-sentence (nonstate-value 'sentence-selection)))
                             (cond ((eq heard-sentence 0)
                                    (format t "Sorry, I don't understand what you are saying.~&")
                                   )
                                   (t
                                    (unless (haltp)
                                      (format t "You entered ~a~&" heard-sentence)
                                      (perceive `((heard-sentence (heard ,heard-sentence))))))))
                           (setf waited-for-one-turn nil)
                           )  ;_ end of the first then condition
                          ((eq op 'speak)
                           (format t "~%Computer speaks ~a.~%Text: ~a~&" speak-sentence sentence)
                           ) ;_ end of the second then condition
                          ((eq op 'listen)
                           (setf waited-for-one-turn t)
                           )) ;_ end of cond statement
                         ))))
                   
  (setf perceive-list '((let ((op (operator-in-state  0))
                              (state (value-in-state 'dialog-state 0 'state-number))
                              )
                          (cond ((eq op 'listen)
                                 (let ((possible-responses (cdr (assoc state *answers*))))
                                   (let ((response-sentences (mapcar 'show-response possible-responses)))
                                     (format t "Enter the human's sentence ~a: " response-sentences)
                                     (let ((sentence (read-line)))
                                       (recognize-sentence sentence)
                                       )
                                   ))
                                 );_ end of the first then condition
                                ) ;_ end of cond statement
                          )))
                              

  (new-type 'state-number :numeric t :discrete t :min 0 :max 200)
  (new-type 'whose-turn :constants '(human computer))

  (predicate 'turn-next-cycle :world 'closed :arguments '((state state) (who whose-turn !)))

  (predicate 'dialog-state :world 'closed :arguments '((state state) (state-number sentence-number !)))
;; To avoid the error Error: Type mismatch in conditional TRANSITION; Variable HEARD used for both types STATE-NUMBER and SENTENCE-NUMBER!

  (predicate 'heard-sentence :world 'closed :perception t :arguments '((heard sentence-number)))

  (predicate 'speak-sentence :world 'closed :arguments '((speak sentence-number !)))

  (wsd-model)

  (conditional 'transition
               :conditions '((state (state (state)))
                             (dialog-state (state-number (state-number)))
                             (heard-sentence (heard (heard)))
                             ;(turn-next-cycle (who computer))
                             ;(selected (state (state)) (operator speak))
                             )
               :actions '((dialog-state (state (state)) (state-number (heard)))
                           )
               :function-variable-names '(state-number heard)
               :function '((1 0 155)
                           (1 155 157)
                           (1 157 159)
                           (1 159 161)
                           (1 161 2)
                           (1 2 4) (1 2 5) (1 2 6)
                           (1 4 10) (1 4 11) (1 4 12)
                           (1 10 15) (1 10 26) (1 10 25)
                           (1 15 167) (1 15 34) (1 15 46)
                           (1 167 169)
                           (1 169 17)
                           (1 17 23) (1 17 47) (1 17 48)
                           (1 23 164)
                           (1 164 28) (1 164 122) (1 164 86)
                           (1 34 28) (1 34 122) (1 34 86)
                           (1 28 36) (1 28 50) (1 28 51)
                           (1 30 36) (1 30 50) (1 30 51)
                           (1 36 38) (1 36 124) (1 36 125)
                           (1 38 165) (1 38 130) (1 38 132)
                           (1 165 129)
                           (1 45 40) (1 45 52) (1 45 53)
                           (1 50 40) (1 50 52) (1 50 53)
                           (1 70 40) (1 70 52) (1 70 53)
                           (1 129 40) (1 129 52) (1 129 53)
                           (1 1 57) (1 1 58) (1 1 59)
                           (1 40 57) (1 40 58) (1 40 59)
                           (1 124 57) (1 124 58) (1 124 59)
                           (1 52 63) (1 52 65) (1 52 66)
                           (1 130 80) (1 130 81) (1 130 82)
                           (1 125 40) (1 125 52) (1 125 53)
                           (1 51 135) (1 51 137) (1 51 138)
                           (1 135 129) (1 135 130) (1 135 132)
                           (1 137 80) (1 137 81) (1 137 82)
                           (1 122 40) (1 122 52) (1 122 53)
                           (1 86 88) (1 86 89) (1 86 90)
                           (1 47 28) (1 47 78) (1 47 86)
                           (1 78 80) (1 78 81) (1 78 82)
                           (1 107 80) (1 107 81) (1 107 82)
                           (1 111 80) (1 111 81) (1 111 82)
                           (1 112 80) (1 112 81) (1 112 82)
                           (1 146 80) (1 146 81) (1 146 82)
                           (1 48 28) (1 48 107) (1 48 108)
                           (1 46 28) (1 46 70) (1 46 71)
                           (1 71 111) (1 71 112) (1 71 113)
                           (1 18 29) (1 18 30) (1 18 46)
                           (1 26 29) (1 26 30) (1 26 46)
                           (1 29 28) (1 29 142) (1 29 143)
                           (1 142 38) (1 142 146) (1 142 147)
                           (1 143 149) (1 143 151) (1 143 153)
                           (1 25 32) (1 25 72) (1 25 73)
                           (1 32 28) (1 32 41) (1 32 42)
                           (1 41 45) (1 41 1) (1 41 76)
                           (1 72 45) (1 72 75) (1 72 76)
                           (1 75 116) (1 75 117) (1 75 118)
                           (1 73 95) (1 73 96) (1 73 97)
                           (1 95 116) (1 95 117) (1 95 118)
                           (1 96 100) (1 96 101) (1 96 102)
                           (1 11 17) (1 11 18) (1 11 25)
                           (1 12 172) (1 12 173) (1 12 20)
                           (1 172 23) (1 172 47) (1 172 48)
                           (1 173 29) (1 173 30) (1 173 46)
                           (1 5 10) (1 5 11) (1 5 12)
                           (1 6 174) (1 6 176) (1 6 12)
                           (1 174 15) (1 174 26) (1 174 25)
                           (1 176 17) (1 176 18) (1 176 25)
                            ))

  (conditional 'speak
               :conditions '((dialog-state (state-number (state-number))))
               :actions '((speak-sentence (speak (speak-sentence))))
               :function-variable-names '(state-number speak-sentence)
               :function '((1 0 171) (1 155 156) (1 157 158) (1 159 160)
                           (1 161 162) (1 2 3) (1 4 7)
                           (1 10 13) (1 15 16) (1 167 168)
                           (1 169 170) (1 17 22) (1 23 163)
                           (1 34 27) (1 164 27)
                           (1 28 35) (1 30 35)
                           (1 36 37)
                           (1 38 128)
                           (1 165 166)
                           (1 45 39) (1 50 39) (1 70 39) (1 129 39)
                           (1 1 56) (1 40 56) (1 124 56)
                           (1 57 60) (1 58 61) (1 59 62)
                           (1 52 55)
                           (1 63 64) (1 65 67) (1 66 68) (1 53 54)
                           (1 130 131)
                           (1 80 83) (1 81 84) (1 82 85) (1 132 133)
                           (1 125 126)
                           (1 51 134)
                           (1 135 136)
                           (1 137 139)
                           (1 138 140)
                           (1 122 123)
                           (1 86 87)
                           (1 88 91)
                           (1 89 92)
                           (1 90 93)
                           (1 47 49)
                           (1 78 79) (1 107 79) (1 111 79) (1 112 79) (1 146 79)
                           (1 48 106)
                           (1 108 109)
                           (1 46 69)
                           (1 71 110)
                           (1 113 127)
                           (1 18 24) (1 26 24)
                           (1 29 141)
                           (1 142 144)
                           (1 147 148)
                           (1 143 145)
                           (1 149 150)
                           (1 151 152)
                           (1 153 154)
                           (1 25 31)
                           (1 32 33)
                           (1 41 44)
                           (1 76 77)
                           (1 42 43)
                           (1 72 74)
                           (1 75 114)
                           (1 116 119)
                           (1 117 120)
                           (1 118 121)
                           (1 73 94)
                           (1 95 115)
                           (1 96 99)
                           (1 100 105)
                           (1 101 104)
                           (1 102 103)
                           (1 97 98)
                           (1 11 14)
                           (1 12 19)
                           (1 172 178)
                           (1 173 179)
                           (1 20 21)
                           (1 5 8)
                           (1 6 9)
                           (1 174 175)
                           (1 176 177)))
#|
  (conditional 'alternate-turns
               :conditions '((turn-next-cycle (who (whose-turn))))
               :actions '((turn-next-cycle (who (whose-turn-next))))
               :function-variable-names '(whose-turn whose-turn-next)
               :function '((1 human computer) (1 computer human)))
|#
  (conditional 'humans-turn
               :conditions '((state (state (state)))
                             (selected (state (state)) (operator speak)))
               :actions '((turn-next-cycle (state (state)) (who human))))

  (conditional 'computers-turn
               :conditions '((state (state (state)))
                             (selected (state (state)) (operator listen)))
               :actions '((turn-next-cycle (state (state)) (who computer))))

  (conditional 'what-to-do
               :conditions '((state (state (state)))
                             (turn-next-cycle (state (state)) (who (whose-turn))))
               :actions '((selected (state (state)) (operator (operator))))
               :function-variable-names '(whose-turn operator)
               :function '((1 human listen) (1 computer speak)))

  (write-out-conditionals)

  (evidence '((dialog-state (state 0) (state-number 0))
              (turn-next-cycle (state 0) (who computer))
            ))

  (format t "Initialization completed.~&")
  (d)
  )
